name: deploy

on:
  push:
    branches:
      - master

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: .
          target: ~/sancathon

  deploy-server:
    needs: [copy-files]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Execute remote command
        uses: appleboy/ssh-action@master
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          GRAPHQL_PORT: ${{ secrets.GRAPHQL_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CI: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: MONGO_URL,GRAPHQL_PORT,JWT_SECRET,CI
          script_stop: true
          script: |
            cd ~/sancathon
            cp packages/server/.env.ci.example .env
            yarn
            yarn server:generate-schema
            yarn server:build
            pm2 start dist --name "graphql"

  deploy-app:
    needs: [copy-files, deploy-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Execute remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: echo "App"
