name: deploy

on:
  push:
    branches:
      - master

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: .
          target: ~/sancathon


  deploy-server:
    needs: [copy-files]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Execute remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/sancathon
            yarn
            yarn server:generate-schema
            yarn server:build
            pm2 restart ~/server_ecosystem.config.js

  deploy-app:
    needs: [copy-files, deploy-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Execute remote command
        uses: appleboy/ssh-action@master
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: GRAPHQL_URL,ACCESS_TOKEN
          script: |
            cd ~/sancathon
            yarn console:relay
            yarn console:build
            sudo service nginx restart
